//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHO_Survey_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyUrl { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> TotalCompanySurvey { get; set; }
        public string CompanyLogo { get; set; }
        public string Company_LandingPageData { get; set; }
        public string DemoGraphicData { get; set; }
        public string DemoGraphicDropDowns { get; set; }
        public string HeadingsAndContents { get; set; }
    }
}
