//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHO_Survey_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponse
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Experience { get; set; }
        public string Work_Place { get; set; }
        public string Contract_Category { get; set; }
        public string Language { get; set; }
        public string SurveyTitle { get; set; }
        public string Responses { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedAt { get; set; }
        public string DeletedAt { get; set; }
        public string DemoGraphicDropDown6 { get; set; }
        public string DemoGraphicDropDown7 { get; set; }
    }
}
